services:
  - type: web
    name: aliexpress-scraper
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SCRAPERAPI_KEY
        sync: false
      - key: SCRAPINGBEE_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
